Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae	3.3973862298		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae	3.35467852737	truc	3.48723280143
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae	0.0		
Archaea.Euryarchaeota.Methanopyri.Methanopyrales	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Jeotgalibacillus	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Paralactobacillus	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerostipes	2.46869660985		
Archaea.Crenarchaeota	0.0		
Bacteria.Bacteroidetes.Sphingobacteria	0.0		
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Mahella	0.0		
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Escherichia_Shigella	3.21605903529	truc	3.76985285179
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae.Bacteroides	4.96077651904		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetivibrio	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Bacillus	0.0		
Bacteria.Bacteroidetes.Flavobacteria	0.0		
Bacteria.Bacteroidetes	5.45124105988	rag2	4.91280166375
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaerovibrio	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Papillibacter	2.61660536138	rag2	4.23356186839
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae	1.69005061574		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae	4.94568210835	truc	4.27494726355
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Lactobacillus	4.63306410911		
Bacteria.Deferribacteres	4.32189541079		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales	2.08166438793		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae	1.79693067035		
Bacteria.Deinococcus_Thermus.Deinococci	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Kurthia	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Butyricicoccus	3.40818996549		
Bacteria.Firmicutes.Clostridia.Clostridiales.Syntrophomonadaceae.Syntrophomonas	0.0		
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae	0.0		
Bacteria.Deferribacteres.Deferribacteres.Deferribacterales.Deferribacteraceae.Geovibrio	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Petrimonas	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae	0.734239083282		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales	3.26058774805		
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales	0.0		
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Slackia	2.39884212637		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales	3.73526947341		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae	1.28377399833		
Bacteria.Proteobacteria.Epsilonproteobacteria	4.56661675106		
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales	1.38247546511		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerofilum	0.0		
Bacteria.Cyanobacteria	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Tetragenococcus	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Facklamia	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae	0.0		
Bacteria.Deferribacteres.Deferribacteres.Deferribacterales.Deferribacteraceae	4.32189541079		
Archaea.Crenarchaeota.Thermoprotei.Desulfurococcales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Tepidibacter	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Globicatella	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobacteraceae.Desulfocella	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Metascardovia	2.98235041465	rag2	3.73648109704
Bacteria.Deinococcus_Thermus.Deinococci.Thermales	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingomonas	0.98573154279		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Oscillibacter	4.03339197996	truc	3.42000344662
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Parasporobacterium	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae	4.2999205244		
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae	1.26095185164		
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Pseudomonas	0.0		
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Planifilum	0.0		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Sediminibacterium	0.0		
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Caldanaerobius	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobulbaceae	0.0		
Bacteria.Deferribacteres.Deferribacteres.Deferribacterales.Deferribacteraceae.Mucispirillum	4.32051781565		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae	4.78975167899	rag2	4.50167496335
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Streptococcus	3.35031060421	truc	3.54347858283
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae	0.0		
Bacteria.Chlamydiae.Chlamydiae.Chlamydiales	0.0		
Archaea.Euryarchaeota.Methanopyri.Methanopyrales.Methanopyraceae.Methanopyrus	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Butyricimonas	2.34396515604		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Scardovia	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Oxalobacter	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales	1.39170954085		
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Thermoflavimicrobium	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Trichococcus	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales	1.93290374608		
Archaea.Crenarchaeota.Thermoprotei.Sulfolobales	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Microbacterium	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Dorea	0.734239083282		
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Helicobacter	4.38660493048		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Bifidobacterium	5.08294403178	rag2	4.79454682732
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae	4.56526350765		
Bacteria.Firmicutes.Clostridia.Clostridiales.Heliobacteriaceae.Heliobacillus	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ethanoligenens	0.681018935505		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae	2.08166438793		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae	4.6891502482		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Sharpea	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Pilibacter	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae	0.806652743612		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Olsenella	1.55541609108		
Bacteria.Verrucomicrobia	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Lachnobacterium	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Nosocomiicoccus	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Rikenella	2.58539982803		
Bacteria.Proteobacteria	4.71817589014		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae	0.750508134276		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae	4.96077651904		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Paenibacillus	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae	3.82897463302		
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae.Gracilibacter	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Isobaculum	0.0		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Nubsella	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acidisphaera	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfohalobiaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Atopobacter	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Parascardovia	0.0		
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Wolinella	2.75706961204		
Bacteria.Deinococcus_Thermus	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Roseburia	3.25987673226	rag2	3.45464257402
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Hydrogenoanaerobacterium	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Acetitomaculum	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria	0.98573154279		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Sinomonas	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Collinsella	2.20888995297		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Natronobacillus	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae.Aeromonas	0.806652743612		
Bacteria.Firmicutes.Clostridia.Clostridiales.Syntrophomonadaceae.Thermosyntropha	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae	1.37986279082		
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Filibacter	0.0		
Bacteria.Proteobacteria.Betaproteobacteria	3.88195792056		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Curtobacterium	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Butyrivibrio	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Moryella	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae.Oceanobacter	0.0		
Archaea	0.0		
Archaea.Euryarchaeota.Methanopyri.Methanopyrales.Methanopyraceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Dialister	1.38902062008		
Bacteria.Firmicutes	5.89356928849	truc	5.12839509515
Archaea.Crenarchaeota.Thermoprotei.Sulfolobales.Sulfolobaceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Lactonifactor	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae	5.32687311818	truc	4.63230953198
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Parabacteroides	3.65259945739	rag2	3.48979706512
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Vulcanibacillus	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Paraeggerthella	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Enterorhabdus	2.79519913411		
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Hahellaceae.Halospina	0.0		
Archaea.Crenarchaeota.Thermoprotei.Thermoproteales.Thermoproteaceae.Caldivirga	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Robinsoniella	0.0		
Bacteria.Aquificae.Aquificae	0.0		
Bacteria.Firmicutes.Clostridia.Halanaerobiales	0.0		
Bacteria.Chlamydiae	0.0		
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Staphylococcus	3.99016212642	rag2	3.58298687858
Bacteria.Deferribacteres.Deferribacteres	4.32189541079		
Bacteria.Aquificae.Aquificae.Aquificales	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales	4.78975167899	rag2	4.50167496335
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Lacticigenium	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Acinetobacter	0.806652743612		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Desulfovibrio	3.17946381228		
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Hahellaceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae.Lutispora	0.0		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Carnobacterium	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Gardnerella	1.05630767289		
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Eubacterium	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria	3.79616394113		
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae	0.0		
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae.Ferrimicrobium	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Syntrophococcus	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Syntrophomonadaceae	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales	3.3973862298		
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae	1.32334657859		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetanaerobacterium	0.607162407334		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Hespellia	0.0		
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Johnsonella	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Aquabacterium	0.0		
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae.Sphaerobacter	0.0		
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae.Rubrobacter	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Ignavigranum	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Abiotrophia	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria	3.27354328726	truc	3.85176080636
Bacteria.Actinobacteria.Actinobacteria	4.80037710901	rag2	4.49352271157
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Plesiomonas	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Catellicoccus	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Pseudobutyrivibrio	1.14020145252		
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Enterococcus	2.12887203835		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Cerasibacillus	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Vagococcus	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactovum	0.0		
Bacteria.TM7	1.24306963169		
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Sporobacterium	1.14020145252		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae	3.26058774805		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopostipes	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Marinilabiaceae.Alkaliflexus	0.0		
Bacteria.Firmicutes.Erysipelotrichi	2.08166438793		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Coprobacillus	1.46255871659		
Archaea.Euryarchaeota.Methanopyri	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae	0.806652743612		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfohalobiaceae.Desulfohalobium	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae	0.98573154279		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Glycomycetaceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerotruncus	2.91968240236		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Faecalibacterium	1.11683085493		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Allobaculum	0.0		
Archaea.Crenarchaeota.Thermoprotei	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae.Corynebacterium	2.01669341204		
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Sulfurimonas	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Proteiniphilum	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales	5.4336858835	rag2	4.91353725872
Bacteria.Firmicutes.Clostridia.Clostridiales.Heliobacteriaceae	0.0		
Bacteria.Fusobacteria.Fusobacteria	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Tepidimonas	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Marinilabiaceae	0.0		
Archaea.Euryarchaeota.Halobacteria	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae	0.0		
Bacteria.Aquificae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae	2.04921596687		
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae	2.32516668349		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Odoribacter	0.0		
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Alloscardovia	2.02704851789		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae	0.0		
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae.Marinithermus	0.0		
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales	4.56599711045		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Holdemania	1.84545040303		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Pediococcus	0.0		
Bacteria.Firmicutes.Bacilli	5.03235797063		
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Jeotgalicoccus	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales	0.98573154279		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Parasutterella	3.731452987		
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Desmospora	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae	1.88192155476		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Adlercreutzia	0.962254870731		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Melissococcus	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis.Phocaeicola	0.0		
Bacteria.Chloroflexi.Thermomicrobia	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales	5.82688406855	truc	5.18194989079
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Saccharibacillus	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Dolosicoccus	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactococcus	1.05491420296		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Hallella	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Desemzia	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Janthinobacterium	1.28377399833		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Frigoribacterium	0.0		
Archaea.Euryarchaeota.Halobacteria.Halobacteriales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Peptostreptococcus	0.806652743612		
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Pseudoramibacter	0.0		
Archaea.Euryarchaeota.Halobacteria.Halobacteriales.Halobacteriaceae	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Klebsiella	0.806652743612		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopococcus	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Seinonella	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Catonella	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Tanticharoenia	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Nocardioides	1.54166437401		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Shuttleworthia	0.0		
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Eggerthella	2.6432321982		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Bavariicoccus	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Asaccharobacter	3.10324229075	truc	3.56084295324
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Propionispira	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales	4.04527770995	rag2	3.64627388681
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Ammonifex	0.0		
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Rhodobacter	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfohalobiaceae.Desulfonatronovibrio	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Leucobacter	1.05153812994		
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae.Thiothrix	1.38247546511		
Bacteria.Bacteroidetes.Bacteroidia	5.4336858835	rag2	4.91353725872
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Trabulsiella	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Salirhabdus	0.0		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cyclobacteriaceae	0.0		
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Kluyvera	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Subdoligranulum	0.639709600214		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis.Rummeliibacillus	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Tannerella	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Dolosigranulum	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ruminococcus	1.14020145252		
Bacteria.Firmicutes.Bacilli.Lactobacillales	4.97658433151		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Coriobacterium	0.0		
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Gordonibacter	1.33844521856		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Lysinibacillus	1.25958467194		
Bacteria.Chlamydiae.Chlamydiae	0.0		
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Rahnella	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae	3.21200708289		
Bacteria.Chloroflexi	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Alistipes	4.24729366291		
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae	1.38902062008		
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Turicibacter	0.0		
Bacteria.Fusobacteria	0.0		
Bacteria.Firmicutes.Clostridia	5.82754191455	truc	5.18068299797
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Coprococcus	1.77888677727		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Xylanibacter	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Lawsonia	2.0023539047		
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Garciella	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Sporosarcina	0.0		
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Thermoanaerobacterium	0.0		
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae	0.0		
Archaea.Crenarchaeota.Thermoprotei.Thermoproteales.Thermoproteaceae	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Sporobacter	0.0		
Bacteria.Acidobacteria	0.0		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae	1.24063437834		
Archaea.Euryarchaeota	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Filifactor	0.0		
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae.Leuconostoc	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Paludibacter	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae	1.38247546511		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Oribacterium	0.0		
Bacteria.Firmicutes.Clostridia.Halanaerobiales.Halanaerobiaceae	0.0		
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae	0.806652743612		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Massilia	0.0		
Archaea.Euryarchaeota.Methanomicrobia	0.0		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Filobacillus	0.0		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales	3.88195792056		
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis	0.0		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerosporobacter	0.0		
Bacteria.Deferribacteres.Deferribacteres.Deferribacterales	4.32189541079		
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis	1.08144546945		
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Marvinbryantia	0.697149787298		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Prevotella	1.53410174333		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Paraprevotella	1.04292813456		
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae	4.0072372728	rag2	3.59912842757
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales	0.806652743612		
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae	0.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Barnesiella	4.76115874461	rag2	4.33432367688
Archaea.Crenarchaeota.Thermoprotei.Thermoproteales	0.0		
Bacteria	6.0		
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae	4.98734918464	rag2	4.5804447218
Bacteria.Actinobacteria	4.80037710901	rag2	4.49352271157
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Verminephrobacter	0.0		
Bacteria.Cyanobacteria.Cyanobacteria	0.0		
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobacteraceae	0.0		
